image: maven:latest

stages:
- build
- run

build:
  stage: build
  script:
  - mvn clean install

run:
  stage: run
  script:
   - docker build -f heroku-web/Dockerfile -t registry.heroku.com/heroku-demo/heroku-web .
   - docker login -u _ -p $HEROKU_PRODUCTION_API_KEY registry.heroku.com
   - docker push registry.heroku.com/heroku-demo/heroku-web